import dev.limebeck.revealkt.core.RevealKt
import dev.limebeck.revealkt.dsl.*
import dev.limebeck.revealkt.dsl.slides.*

title = "RevealKt: themes, assets and sharing"
configuration {
    theme = RevealKt.Configuration.Theme.Custom("assets/theme.css")
    slideNumber = RevealKt.Configuration.SlideNumber.Custom("c/t")
    pdfSeparateFragments = false
}
slides {
    regularSlide {
        +title { "Your slides, your visual language" }
        +regularText { "The colors, type and spacing you see come from a local CSS file. Custom themes replace the built-in theme." }
        +code(lang = "kotlin") {
            """
            configuration {
                theme = RevealKt.Configuration.Theme.Custom("assets/theme.css")
            }
            """.trimIndent()
        }
        +note { "Use additionalCssStyle for small overrides when keeping a built-in theme." }
    }
    regularSlide {
        +title { "Local SVG, real assets" }
        +img(src = "pipeline.svg") { width = 780; stretch = false }
        +code(lang = "kotlin") { "+img(src = \"pipeline.svg\") { width = 780; stretch = false }" }
        +regularText { "The DSL adds assets/ to image paths. The CLI copies this SVG and the CSS into the HTML bundle." }
    }
    regularSlide {
        +title { "A link your audience can take" }
        +row {
            column {
                +qrCode("https://limebeck.github.io/reveal-kt/") { width = 220; height = 220; stretch = false }
            }
            column {
                +regularText { "Scan this real QR code to open the documentation. RevealKt generates the image at build time." }
                +code(lang = "kotlin") { "+qrCode(url) { width = 220; stretch = false }" }
            }
        }
    }
    regularSlide {
        +title { "One script. Two ways to share." }
        +code(lang = "bash") {
            """
            revealkt bundle Talk.reveal.kts --output-dir out
            revealkt chrome install
            revealkt pdf Talk.reveal.kts -o Talk.pdf
            """.trimIndent()
        }
        +unorderedListOf("HTML keeps navigation, fragments and speaker notes.", "PDF captures the slides; it needs Chromium.", "Publish the entire HTML directory, including assets.", fragmented = false)
        +regularText { "You are viewing a real bundle generated by the site's buildSite task." }
    }
}
